name = "vdist-solver-fortran"
version = "1.4.2"
license = "Apache License Version 2.0"
author = "Nkzono99"
maintainer = "210x218x@stu.kobe-u.ac.jp"
copyright = "Copyright 2024, Nkzono99"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[dependencies]
futils = { git = "https://github.com/Nkzono99/futils" }
finbound = { git = "https://github.com/Nkzono99/finbound" }
forbear = { git = "https://github.com/szaghi/forbear.git" }

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
